In [6]:
import numpy as np


In [12]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [8]:
type(a)

numpy.ndarray

basic operations of array

print(a+b)

In [13]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


creating more than 1d array

In [14]:
#creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [15]:
print(a2.shape)

(2, 3)


In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
array = np.random.randint(1,11, size = (3,4))
print(array)

[[10  1  5  4]
 [ 3  5  2  1]
 [ 7  4  3  6]]


In [24]:
x = np.array([[7,6,4],
              [4,6,5],
              [5,6,4]])
y = np.array([[3,4,5],
              [8,9,5],
              [8,9,6]])
print(x)
print(y)

[[7 6 4]
 [4 6 5]
 [5 6 4]]
[[3 4 5]
 [8 9 5]
 [8 9 6]]


In [25]:
print(x@y)#matrix multipication


[[101 118  89]
 [100 115  80]
 [ 95 110  79]]


In [26]:
print(x*y)

[[21 24 20]
 [32 54 25]
 [40 54 24]]


In [29]:
x.prod() #product of all elements

np.int64(2419200)

In [34]:
np.dot(x,y)

array([[101, 118,  89],
       [100, 115,  80],
       [ 95, 110,  79]])

In [35]:
x.mean()#mean of all elements

np.float64(5.222222222222222)

In [36]:
y.mean()

np.float64(6.333333333333333)